### PR TITLE
improve robustness for approvalrule.pp

### PR DESCRIPTION
**Pull request by kreeuwijk**
The proposed changes will improve the robustness of the approvalrule.pp manifest. With the original code, I ran into the issue that if the WSUS server is low on memory, sometimes `Get-WsusServer` fails to complete. This will trip up the `unless` rule and make Puppet think it needs to re-apply the approval rule. This results in multiple identical copies of the same rule, which trips up other code that isn't expecting >1 result for a specific rule query.

The new code switches to `onlyif` to account for the occasional failure in `Get-WsusServer` and not have it result in duplicate rules.

### CODE REVIEW

**Comment by TraGicCode** [comment]
Hey,

Sorry for getting back to this so late.  I will give this a review by tommorow!

**Comment by kreeuwijk** [comment]
Thanks @TraGicCode !

**Review by TraGicCode — APPROVED** [review]
LGTM and thank you!

**Comment by kreeuwijk** [comment]
Thanks! Can you republish the module on the Forge too?
That way everybody can enjoy it :-)

*Kevin Reeuwijk*
Principal Sales Engineer, NEMEA
mobile: +31 6 272 33 55 1
kevinr@puppet.com <kevin.reeuwijk@puppet.com> | @KevinReeuwijk
*Puppet <http://www.puppet.com>. The shortest path to better software.*

**Comment by kreeuwijk** [comment]
Hi Michael,

I've published a blogpost
<https://puppet.com/blog/how-automate-windows-patching-puppet> on the
puppet.com website that uses your wsusserver module.
The example code in the blogpost uses the product_families attribute which
is in v1.1.1 of your module. But that module isn't published on the Forge
yet.
Could you please publish this version?

Thank you!

*Kevin Reeuwijk*
Principal Sales Engineer, NEMEA
mobile: +31 6 272 33 55 1
kevinr@puppet.com <kevin.reeuwijk@puppet.com> | @KevinReeuwijk

*Puppet <http://www.puppet.com>. The shortest path to better software.*
J*oin us for Puppetize PDX <http://www.puppet.com/puppetize> 9-10 October.*

**Pull request merged**
