### PR TITLE
(GH-47) wsus-config-update-products: Fixes Duplicate Product Name Selection

### LINKED ISSUE #46: Windows Server 2019 and 10 product is not correctly chosen anymore due to duplicate products being listed
This is more the fault of MS and their crappy naming conventions but the 'wsus-config-update-products' does not select Windows Server 2019 correctly. The reason is because MS stupidly has two products listed with the name "Windows Server 2019". You can see this if you run the command `(Get-WsusServer).GetUpdateCategories() | where { $_.Type -eq 'Product' } | findstr /i 2019`

You will see there is a Windows Server 2019 with description "Category for Windows Server 2019" as well as a second one with description "Windows Server 2019 (RS5 Server) and above". The exec routine chooses the first one, but when looking in the WSUS Management Console the desired product is not checked off as it actually uses the other Windows Server 2019 product with the second description.

### PR DESCRIPTION
**Pull request by amr952**
#### This Pull Request (PR) fixes the following issues
 Fixes #46 

#### Task list

- [ ] Resource/Class documentation added/updated in README.md?
- [ ] Examples appropriately added/updated?
- [ ] Unit tests added/updated?
- [ ] Integration tests added/updated (where possible)?

### CODE REVIEW

**Comment by TraGicCode** [comment]
Hey @amr952 ,

Thank you for the pull request.  Is there an already open issue that i can link to this pull-request?  If not can you create one that describes the problem so i can use that when i create the changelog for the new version of the module?

Thanks

**Review by TraGicCode — CHANGES_REQUESTED** [review]
Hey @amr952 ,

Thank you for the pull request. Is there an already open issue that i can link to this pull-request? If not can you create one that describes the problem so i can use that when i create the changelog for the new version of the module?

Thanks

**Comment by TraGicCode** [comment]
Hey @amr952 ,

Just pinging you again since i haven't heard back from you about my initial request above.

**Comment by mike406** [comment]
Hi @TraGicCode please do not merge this request just yet. @amr952 and I are testing out files that I sent him in our production environments. Once he reports back we can discuss the PR. Thank you.

**Comment by TraGicCode** [comment]
Hey @mike406 ,

I will hold off until given the thumbs up.

Thank you

**Comment by mike406** [comment]
@amr952 Following up on this PR. Are we good to go on it?

**Comment by mike406** [comment]
@TraGicCode We can go ahead with this PR. It passes all of my tests.

**Comment by mike406** [comment]
@TraGicCode We can go ahead with this PR. It passes all of my tests.

**Comment by amr952** [comment]
I agree - This was been working great for me for the past few weeks.

**Comment by mike406** [comment]
@TraGicCode We are ready to go forward with this PR. It passes all of my tests.

**Pull request merged**
