### PR TITLE
wsusserver: Support nesting of computer_target_groups and replica servers

### PR DESCRIPTION
**Pull request by stowill**
#### Pull Request (PR) description

Adds the ability to have nested computer target groups

#### This Pull Request (PR) fixes the following issues

n/a

#### Task list

- [x] Resource/Class documentation added/updated in README.md?
- [x] Examples appropriately added/updated?
- [x] Unit tests added/updated?
- [ ] Integration tests added/updated (where possible)?

### CODE REVIEW

**Comment by stowill** [comment]
Added a fix to the updatesyncsettings that Nathan hadn't done a pull request for

**Comment by TraGicCode** [comment]
Hey @stowill ,

Thanks for the pull request. Changes for wanting to implement this feature as it's definitely one that is missing.

I would like to propose a change to how the child groups are created under parent groups.  

I think we should add a new attribute to the `wsusserver_computer_target_group` type called parent_group ( just like the documentation https://docs.microsoft.com/en-us/previous-versions/windows/desktop/aa349860%28v%3dvs.85%29 ) that defaults to a value of `All Computers`.

I also think this recommendation would reduce complexity in the maintainability of the code in the future.

**Comment by stowill** [comment]
Hi @TraGicCode, 

That sounds like a good idea. I'm just wondering how that would be reflected in the declaration syntax.
The syntax I have proposed would show all the levels in one entry:
```puppet
wsusserver_computer_target_group { ['Common\\Special App\\Deeper Level']:
    ensure => 'present',
}
```
Can you please provide an example of the syntax you are thinking of and I'll work towards that?

If you're thinking of something like:
```puppet
wsusserver_computer_target_group { 
    [
        {Name => 'Common', Parent => 'All Computers'},
        {Name => 'Special App', Parent => 'Common'},
        {Name => 'Deeper Level', Parent => 'Special App'}
    ]:
    ensure => 'present',
```
then I think this might be confusing and may lead to errors.

Depending on the order the above entries get processed you could end up with ```Special App``` under ```All computers``` or an error because ```Special App``` hasn't yet been created. 

This in turn might produce an error when trying to create ```Special App``` under ```Common``` which now exists elsewhere in the tree and duplicate names aren't allowed. I hope that makes sense. :-) 

Also what's required at the API layer may not necessarily translate to a good user experience.

I have colleagues who aren't interested in the API requirements; just something that makes sense to them at the hiera level.

I also left "All Computers" out as it made the code easier.

**Comment by stowill** [comment]
Forgive me if I have some of the terminology and syntax incorrect.

I've only been using Puppet for a few months.

**Comment by TraGicCode** [comment]
Hey @stowill ,

The Types and Providers should be capable of setting up relationships and dependencies so that parents get created first regardless of ordering within the manifest.

If i were to take a stab at the public interface for this feature i would think it would be similar to what you post

```puppet
wsusserver_computer_target_group { 'Azure':
    ensure => 'present',
   # parent_group => 'All Computers' Default so not explicitly needed
}

wsusserver_computer_target_group { 'Amazon':
    ensure => 'present',
   # parent_group => 'All Computers' Default so not explicitly needed
}


wsusserver_computer_target_group { 'Development':
    ensure => 'present',
    parent_group => 'Azure',
}

wsusserver_computer_target_group { 'Development':
    ensure => 'present',
    parent_group => 'Amazon',
}

```

**Comment by stowill** [comment]
Hi @TraGicCode ,

In relation to the discussion about how to declare the computer target groups I don't think it will work using what you have proposed based on my suggested example.
From what I remember in my reading on Puppet all resource declarations need to be unique.
Your example has highlighted an issue with the proposed declaration syntax. 
The following is going to fail as it's been repeated:

```puppet
wsusserver_computer_target_group { 'Development': ...
```

That's why `Path` is the namevar for the `File` resource which has to be fully qualified.

I'm now leaning towards my original syntax as described in the [Readme](https://github.com/stowill/tragiccode-wsusserver/blob/feature/support-nested-target-groups/README.md#creating-computer-target-groups). I don't believe we need to provide the parent path. 
The whole concept of Puppet types and providers is to abstract the implementation details away from the user of the resource.

To me it makes more sense to declare the computer target group structure in a format that matches existing Puppet resources (eg: [File](https://puppet.com/docs/puppet/latest/types/file.html#file-attribute-path)) as well as looking similar to how the GUI displays the information.

I've also been doing some work on getting the module to support replica servers which is in the latest commit. There's lots of extra code to digest because of it.

Appveyor is also failing the checks as it looks like "activesupport" requires Ruby 2.5.0.

**Comment by TraGicCode** [comment]
> From what I remember in my reading on Puppet all resource declarations need to be unique.

You are indeed correct.  I agree your original solution seems most appropriate!


> I've also been doing some work on getting the module to support replica servers which is in the latest commit

Let me take a quick look

> Appveyor is also failing the checks as it looks like "activesupport" requires Ruby 2.5.0.

I can also take a look at this.  I do need to update this module to use PDK.  I was holding back for the longest time because PDK didn't support beaker.

**Comment by TraGicCode** [comment]
Hey @stowill ,

Are u able to resolve the conflicts and get this pushed through still?

**Comment by stowill** [comment]
Hi TragicCode,

Sorry for taking so long to reply. The email got lost in my inbox.

Unfortunately I stopped using Puppet over 12 months ago and no longer have
the environment to test things in so I can't assist.

I've also forgotten what I was trying to do anyway.

Cheers,
stowill

**Pull request closed without merging**
